### ISSUE TITLE
Failed to determine local data path on Debian

### ISSUE THREAD

**Issue by feugen** [MHeasell/rwe#47]
Hello,

I tried to run rwe on debian and it crashes. rwe::getLocalDataPath() cant find anything because its looking for "APPDATA" and its not available on Linux.

Isnt argv[0] a better solution, ofcourse combined with  boost::filesystem? 

Once I get the data files, I will try to launch the application and later ill try to contribute something. Btw I had to install libPNG-dev on my Debian, to be able to compile and its not mentioned in your tutorial - probably there are some differences between debian/ubuntu.

Thanks for all your work you have done so far :-)

**Comment by MHeasell** [comment]
Hi, thanks for opening this.

I've changed the Linux version to read from `$HOME/.rwe/Data` (in f23f6c92e51d1a2cfaa75aa288101fe4815b82a2). This should unblock things.

You're right, libpng was missing from the list of dependencies. I've added it in d630f0794026f1b952582b05063689d2fb6c42af.

Unfortunately, on Ubuntu RWE now crashes for me on startup for a different reason. I've opened #48 to investigate this.
