### ISSUE TITLE
Unable to Change Screen Resolution

### ISSUE THREAD

**Issue by LuciusOctavia** [MHeasell/rwe#50]
**Version:** Robot War Engine v0.1.0-707-g14f5663 (release)
Changing resolution is currently not possible in the latest build. 

Following up with a question, will resolution changing be through Singleplayer options, or by some exterior means?
Secondly, if the resolution changing is via Singleplayer options, will it be automatic, or require a restart?

**Comment by MHeasell** [comment]
As a first pass it would be nice to support controlling resolution via command-line arguments. Later this could become a setting read from a config file.

It seems unlikely that the options screen will be implemented inside RWE any time soon. However maybe the launcher could support configuring settings like this.

**Comment by MHeasell** [comment]
I've added command-line options in d1a3c2c59334a28b3275a811f25de44d59dea061. Still need a way of letting the user control this.

**Comment by MHeasell** [comment]
Added a config screen to the launcher that configures this

https://github.com/MHeasell/rwe/commit/541312ba6e491028f45fceeaa0ca66242af41c50
