### ISSUE TITLE
Handling Multiple Game Instances

### ISSUE THREAD

**Issue by LuciusOctavia** [MHeasell/rwe#51]
**Version:** Robot War Engine v0.1.0-707-g14f5663 (release)
**Issue:** If the user tries to launch another instance of the engine, an error will occur with Visual C++ Runtime.
**Image of Issue:** https://gyazo.com/28eb359bff9c33a58a8f2c1eabce8bcb
**Log:** N/A (No response in the log about the occurance).

Preferably, perhaps running the .exe again would divert back to the already running instance, or notify the user an instance of the application is already running.

**Comment by MHeasell** [comment]
For basic network testing it's useful to be able to run multiple instances on one machine so I'll just make that possible.
