### ISSUE TITLE
Unnecessary Pathway Calculation/Invalid Movements

### ISSUE THREAD

**Issue by LuciusOctavia** [MHeasell/rwe#53]
**NOTICE:** This may be a duplicate with #28, will need clarification.

**Version:** Robot War Engine v0.1.0-707-g14f5663 (release)
**Issue:** When the player issues a command to a unit to go to the exact location of a tree, the unit walks continuously into the tree and multiple unnecessary pathways appear.
To clarify... the commander when issued the command was initially behind the tree. To move to the front part of the tree, he circled around and walked continuously into the tree.
**Image of Issue:** https://gyazo.com/fe10536c78cb01e5b5cbf6056859da35
**Log:** https://pastebin.com/Cf1tvMvd

Preferably, perhaps running the .exe again would divert back to the already running instance, or notify the user an instance of the application is already running.

**Comment by MHeasell** [comment]
Yes, this will be addressed by #28, closing this as duplicate.
