### ISSUE TITLE
Failed to open file: shaders/basicColor.vert

### ISSUE THREAD

**Issue by feugen** [MHeasell/rwe#64]
Hello, I am on manjaro linux and the project builds just fine but I cant lanuch the application because I get an error: Failed to open file: shaders/basicColor.vert

probably I miss some TA files? I got TA from steam and the Data directory contains only some .ZRB files. All other .ufo. .hpi, .ccx files are from the main ta folder, so my Data directory contains the following files:
1.ZRB      AFlea.ufo    ccmiss.ccx    Example.ufo   tactics3.hpi  totala1.hpi
2.zrb      AScarab.ufo  Cometctr.ufo  floggen.ufo   tactics4.hpi  totala2.hpi
3.ZRB      btdata.ccx   Cormabm.ufo   Mndsmars.ufo  tactics5.hpi  totala3.hpi
4.ZRB      btmaps.ccx   CorNecro.ufo  rev31.gp3     tactics6.hpi  totala4.hpi
5.zrb      ccdata.ccx   corplas.ufo   tactics1.hpi  tactics7.hpi  worlds.hpi
AFark.ufo  ccmaps.ccx   Evadrivd.ufo  tactics2.hpi  tactics8.hpi

Do I miss something or is it some other issue?

**Comment by MHeasell** [comment]
When RWE starts it looks for these shader files relative to its working
directory. These files are not game data, they  are included in the RWE
source tree. For development, run RWE with its working directory set to the
top level of the git repo.

When there is an install package for RWE on Linux I imagine this will have
to change, or perhaps there could be a wrapper script to launch RWE with
the correct working directory so that it finds these files. Would be happy
to receive a patch here.

**Comment by feugen** [comment]
Hey, thanks for your reply,

I just moved the shaders folder from rwe folder to my build folder and I was able to start the game... About the patch... as I see it, it depends on each setup. The way people check out your project could be different every time... The way I did it, was to create a folder and inside the main folder I have an rwe folder and build folders... but it could be anything. Well I guess I could look into this some day... 

I got some more questions... 
1) Is there a way to change any settings like resolution? I am on 4k 24" monitor and I get a tiny window. 2) What is the purpose for "launcher"? why dont you use the multiplayer lobby? How can I run it? Is there any doc file?

**Comment by MHeasell** [comment]
> Is there a way to change any settings like resolution? I am on 4k 24" monitor and I get a tiny window.

No, right now it's hard-coded to 800x600. Have a look in issue #50.

> 2) What is the purpose for "launcher"? why dont you use the multiplayer lobby? How can I run it? Is there any doc file?

The launcher has so far gone undocumented, except for progress updates and discussion in the TAUniverse forum thread.

I have added a new section to the README file for the launcher which explains the purpose, motivation, how to build and run it. Hopefully you'll find this useful.

The launcher has not yet been made to work on Linux. In theory the code should be portable already, it's just that the launcher tries to invoke RWE and the rwe_bridge program as `rwe.exe` and `rwe_bridge.exe` respectively, and these binaries won't have that extension on Linux.
